// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Person.proto

package com.example.protos;

public interface PersonOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protobuf.Person)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int32 age = 1;</code>
   * @return Whether the age field is set.
   */
  boolean hasAge();
  /**
   * <code>optional int32 age = 1;</code>
   * @return The age.
   */
  int getAge();

  /**
   * <code>optional string firstName = 2;</code>
   * @return Whether the firstName field is set.
   */
  boolean hasFirstName();
  /**
   * <code>optional string firstName = 2;</code>
   * @return The firstName.
   */
  java.lang.String getFirstName();
  /**
   * <code>optional string firstName = 2;</code>
   * @return The bytes for firstName.
   */
  com.google.protobuf.ByteString
      getFirstNameBytes();

  /**
   * <code>optional string lastName = 3;</code>
   * @return Whether the lastName field is set.
   */
  boolean hasLastName();
  /**
   * <code>optional string lastName = 3;</code>
   * @return The lastName.
   */
  java.lang.String getLastName();
  /**
   * <code>optional string lastName = 3;</code>
   * @return The bytes for lastName.
   */
  com.google.protobuf.ByteString
      getLastNameBytes();

  /**
   * <code>optional string email = 4;</code>
   * @return Whether the email field is set.
   */
  boolean hasEmail();
  /**
   * <code>optional string email = 4;</code>
   * @return The email.
   */
  java.lang.String getEmail();
  /**
   * <code>optional string email = 4;</code>
   * @return The bytes for email.
   */
  com.google.protobuf.ByteString
      getEmailBytes();
}
