// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Person.proto

package com.example.protos;

public final class PersonProtos {
  private PersonProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_Person_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protobuf_Person_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_Person_Address_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protobuf_Person_Address_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_Person_Employee_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protobuf_Person_Employee_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_Person_Employee_Address_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protobuf_Person_Employee_Address_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014Person.proto\022\010protobuf\"\306\002\n\006Person\022\013\n\003a" +
      "ge\030\001 \001(\005\022\021\n\tfirstName\030\002 \001(\t\022\020\n\010lastName\030" +
      "\003 \001(\t\022\r\n\005email\030\004 \001(\t\032a\n\007Address\022\024\n\014addre" +
      "ssLine1\030\001 \001(\t\022\024\n\014addressLine2\030\002 \001(\t\022\014\n\004c" +
      "ity\030\003 \001(\t\022\017\n\007country\030\004 \001(\t\022\013\n\003zip\030\005 \001(\005\032" +
      "\227\001\n\010Employee\022\022\n\nemployeeId\030\001 \001(\005\022\024\n\014empl" +
      "oyerName\030\002 \001(\t\032a\n\007Address\022\024\n\014addressLine" +
      "1\030\001 \001(\t\022\024\n\014addressLine2\030\002 \001(\t\022\014\n\004city\030\003 " +
      "\001(\t\022\017\n\007country\030\004 \001(\t\022\013\n\003zip\030\005 \001(\005B$\n\022com" +
      ".example.protosB\014PersonProtosP\001"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_protobuf_Person_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protobuf_Person_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protobuf_Person_descriptor,
        new java.lang.String[] { "Age", "FirstName", "LastName", "Email", });
    internal_static_protobuf_Person_Address_descriptor =
      internal_static_protobuf_Person_descriptor.getNestedTypes().get(0);
    internal_static_protobuf_Person_Address_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protobuf_Person_Address_descriptor,
        new java.lang.String[] { "AddressLine1", "AddressLine2", "City", "Country", "Zip", });
    internal_static_protobuf_Person_Employee_descriptor =
      internal_static_protobuf_Person_descriptor.getNestedTypes().get(1);
    internal_static_protobuf_Person_Employee_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protobuf_Person_Employee_descriptor,
        new java.lang.String[] { "EmployeeId", "EmployerName", });
    internal_static_protobuf_Person_Employee_Address_descriptor =
      internal_static_protobuf_Person_Employee_descriptor.getNestedTypes().get(0);
    internal_static_protobuf_Person_Employee_Address_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protobuf_Person_Employee_Address_descriptor,
        new java.lang.String[] { "AddressLine1", "AddressLine2", "City", "Country", "Zip", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
